"""Shared display names for capability-driven TYDOM entities.

Translation keys affect presentation only. Raw TYDOM attributes, entity unique
identifiers, commands and values must never be derived from translated names.
"""

from __future__ import annotations

from contextlib import suppress
from dataclasses import replace
import re
from typing import Any

from homeassistant.helpers.entity import EntityDescription

ENTITY_NAMES: dict[str, str] = {
    "tywell_weather_condition": "Weather",
    "tywell_weather_daily_power": "Daily power",
    "tywell_weather_max_daily_outdoor_temperature": "Daily maximum outdoor temperature",
    "tywell_weather_outdoor_temperature": "Outdoor temperature",
    "tywell_weather_power": "Power",
    "absence": "Away mode",
    "absencesetpoint": "Away temperature",
    "absmaxcoolsetpoint": "Maximum cooling setpoint",
    "absmaxheatsetpoint": "Maximum heating setpoint",
    "absmincoolsetpoint": "Minimum cooling setpoint",
    "absminheatsetpoint": "Minimum heating setpoint",
    "ackeventcmd": "Event acknowledgement command",
    "acknowledge_events": "Acknowledge events",
    "activationcpt": "Activation count",
    "activationindex": "Activation index",
    "alarmcmd": "Alarm command",
    "alarmintrusion": "Intrusion",
    "alarmmode": "Alarm mode",
    "alarmsos": "SOS alarm",
    "alarmstate": "Alarm state",
    "alarmtechnical": "Technical alarm",
    "ambienttemperature": "Room temperature",
    "anticipcoeff": "Anticipation coefficient",
    "anticpcoeff": "Anticipation coefficient",
    "antifroston": "Frost protection",
    "antifrostsetpoint": "Frost protection temperature",
    "antifrostwhenoff": "Frost protection",
    "antiseizurecmd": "Anti-seizing command",
    "antiseizureperiod": "Anti-seizing interval",
    "api_mode": "API mode",
    "area_id": "Area identifier",
    "association_category": "1. Category to associate",
    "association_channel": "3. Channel to associate",
    "association_guide": "5. Show association guide",
    "association_mode": "Start association mode",
    "association_name": "Device name (optional)",
    "association_product": "2. Product to associate",
    "association_usage": "4. Usage / association type",
    "authorization": "Authorisation",
    "batt_defect": "Battery fault",
    "battdefect": "Battery fault",
    "batterycmddefect": "Battery command fault",
    "battlevel": "Battery level",
    "bdd_empty": "Database empty",
    "bdd_status": "Database status",
    "boost": "Boost",
    "booston": "Boost",
    "bootreference": "Bootloader reference",
    "bootversion": "Bootloader version",
    "brightness": "Brightness",
    "calibrationdefect": "Calibration defect",
    "cancel_boost": "Cancel Boost",
    "clock": "Gateway time",
    "clock_source": "Clock source",
    "cmddefect": "Command defect",
    "comfortmode": "Comfort mode",
    "config": "Configuration",
    "configsensor": "Sensor configuration",
    "configtemp": "Temperature configuration",
    "coolsetpoint": "Cooling setpoint",
    "current": "Current",
    "currentpower": "Power",
    "currentsetpoint": "Temperature setpoint",
    "dailypower": "Daily power",
    "delaysetpoint": "Setpoint delay",
    "delaythermiclevel": "Heating level delay",
    "device_endpoint": "Endpoint",
    "device_id": "TYDOM endpoint identifier",
    "device_name": "Device name",
    "device_type": "Device type",
    "direction": "Direction",
    "down_defect": "Lower not authorised",
    "downdefect": "Lower not authorised",
    "energy": "Energy",
    "energydistrib": "Consumption share",
    "energydistrib_elec_a": "Current (Electricity)",
    "energydistrib_elec_cooling": "Consumption share (Electricity, Cooling)",
    "energydistrib_elec_heating": "Consumption share (Electricity, Heating)",
    "energydistrib_elec_hotwater": "Consumption share (Electricity, Hot water)",
    "energydistrib_elec_other": "Consumption share (Electricity, Other)",
    "energydistrib_elec_outlet": "Consumption share (Electricity, Outlets)",
    "energydistrib_elec_total": "Consumption share (Electricity, Total)",
    "energydistrib_elec_w": "Power (Electricity)",
    "energydistrib_gas_a": "Current (Gas)",
    "energydistrib_gas_cooling": "Consumption share (Gas, Cooling)",
    "energydistrib_gas_heating": "Consumption share (Gas, Heating)",
    "energydistrib_gas_hotwater": "Consumption share (Gas, Hot water)",
    "energydistrib_gas_other": "Consumption share (Gas, Other)",
    "energydistrib_gas_outlet": "Consumption share (Gas, Outlets)",
    "energydistrib_gas_total": "Consumption share (Gas, Total)",
    "energydistrib_gas_w": "Power (Gas)",
    "energydistrib_gaz_a": "Current (Gas)",
    "energydistrib_gaz_cooling": "Consumption share (Gas, Cooling)",
    "energydistrib_gaz_heating": "Consumption share (Gas, Heating)",
    "energydistrib_gaz_hotwater": "Consumption share (Gas, Hot water)",
    "energydistrib_gaz_other": "Consumption share (Gas, Other)",
    "energydistrib_gaz_outlet": "Consumption share (Gas, Outlets)",
    "energydistrib_gaz_total": "Consumption share (Gas, Total)",
    "energydistrib_gaz_w": "Power (Gas)",
    "energydistrib_water_a": "Current (Water)",
    "energydistrib_water_cooling": "Consumption share (Water, Cooling)",
    "energydistrib_water_heating": "Consumption share (Water, Heating)",
    "energydistrib_water_hotwater": "Consumption share (Water, Hot water)",
    "energydistrib_water_other": "Consumption share (Water, Other)",
    "energydistrib_water_outlet": "Consumption share (Water, Outlets)",
    "energydistrib_water_total": "Consumption share (Water, Total)",
    "energydistrib_water_w": "Power (Water)",
    "energyhisto": "Consumption history",
    "energyhisto_elec_a": "Current (Electricity)",
    "energyhisto_elec_cooling": "Consumption history (Electricity, Cooling)",
    "energyhisto_elec_heating": "Consumption history (Electricity, Heating)",
    "energyhisto_elec_hotwater": "Consumption history (Electricity, Hot water)",
    "energyhisto_elec_other": "Consumption history (Electricity, Other)",
    "energyhisto_elec_outlet": "Consumption history (Electricity, Outlets)",
    "energyhisto_elec_total": "Consumption history (Electricity, Total)",
    "energyhisto_elec_w": "Power (Electricity)",
    "energyhisto_gas_a": "Current (Gas)",
    "energyhisto_gas_cooling": "Consumption history (Gas, Cooling)",
    "energyhisto_gas_heating": "Consumption history (Gas, Heating)",
    "energyhisto_gas_hotwater": "Consumption history (Gas, Hot water)",
    "energyhisto_gas_other": "Consumption history (Gas, Other)",
    "energyhisto_gas_outlet": "Consumption history (Gas, Outlets)",
    "energyhisto_gas_total": "Consumption history (Gas, Total)",
    "energyhisto_gas_w": "Power (Gas)",
    "energyhisto_gaz_a": "Current (Gas)",
    "energyhisto_gaz_cooling": "Consumption history (Gas, Cooling)",
    "energyhisto_gaz_heating": "Consumption history (Gas, Heating)",
    "energyhisto_gaz_hotwater": "Consumption history (Gas, Hot water)",
    "energyhisto_gaz_other": "Consumption history (Gas, Other)",
    "energyhisto_gaz_outlet": "Consumption history (Gas, Outlets)",
    "energyhisto_gaz_total": "Consumption history (Gas, Total)",
    "energyhisto_gaz_w": "Power (Gas)",
    "energyhisto_water_a": "Current (Water)",
    "energyhisto_water_cooling": "Consumption history (Water, Cooling)",
    "energyhisto_water_heating": "Consumption history (Water, Heating)",
    "energyhisto_water_hotwater": "Consumption history (Water, Hot water)",
    "energyhisto_water_other": "Consumption history (Water, Other)",
    "energyhisto_water_outlet": "Consumption history (Water, Outlets)",
    "energyhisto_water_total": "Consumption history (Water, Total)",
    "energyhisto_water_w": "Power (Water)",
    "energyindex": "Consumption index",
    "energyindex_elec_a": "Current (Electricity)",
    "energyindex_elec_cooling": "Consumption index (Electricity, Cooling)",
    "energyindex_elec_heating": "Consumption index (Electricity, Heating)",
    "energyindex_elec_hotwater": "Consumption index (Electricity, Hot water)",
    "energyindex_elec_other": "Consumption index (Electricity, Other)",
    "energyindex_elec_outlet": "Consumption index (Electricity, Outlets)",
    "energyindex_elec_total": "Consumption index (Electricity, Total)",
    "energyindex_elec_w": "Power (Electricity)",
    "energyindex_gas_a": "Current (Gas)",
    "energyindex_gas_cooling": "Consumption index (Gas, Cooling)",
    "energyindex_gas_heating": "Consumption index (Gas, Heating)",
    "energyindex_gas_hotwater": "Consumption index (Gas, Hot water)",
    "energyindex_gas_other": "Consumption index (Gas, Other)",
    "energyindex_gas_outlet": "Consumption index (Gas, Outlets)",
    "energyindex_gas_total": "Consumption index (Gas, Total)",
    "energyindex_gas_w": "Power (Gas)",
    "energyindex_gaz_a": "Current (Gas)",
    "energyindex_gaz_cooling": "Consumption index (Gas, Cooling)",
    "energyindex_gaz_heating": "Consumption index (Gas, Heating)",
    "energyindex_gaz_hotwater": "Consumption index (Gas, Hot water)",
    "energyindex_gaz_other": "Consumption index (Gas, Other)",
    "energyindex_gaz_outlet": "Consumption index (Gas, Outlets)",
    "energyindex_gaz_total": "Consumption index (Gas, Total)",
    "energyindex_gaz_w": "Power (Gas)",
    "energyindex_water_a": "Current (Water)",
    "energyindex_water_cooling": "Consumption index (Water, Cooling)",
    "energyindex_water_heating": "Consumption index (Water, Heating)",
    "energyindex_water_hotwater": "Consumption index (Water, Hot water)",
    "energyindex_water_other": "Consumption index (Water, Other)",
    "energyindex_water_outlet": "Consumption index (Water, Outlets)",
    "energyindex_water_total": "Consumption index (Water, Total)",
    "energyindex_water_w": "Power (Water)",
    "energyindexcoolwatt": "Energy (Cooling)",
    "energyindexdhwwatt": "Energy (Hot water)",
    "energyindexecswatt": "Energy (Hot water)",
    "energyindexheatgas": "Consumption index (Gas, Heating)",
    "energyindexheatwatt": "Energy (Heating)",
    "energyindexti1": "Consumption index (TI1)",
    "energyindexti1watt": "Energy (TI1)",
    "energyindextotelecwatt": "Energy (Electricity)",
    "energyinstant": "Instantaneous consumption",
    "energyinstant_elec_a": "Current (Electricity)",
    "energyinstant_elec_a_max": "Current (Electricity) (maximum)",
    "energyinstant_elec_a_min": "Current (Electricity) (minimum)",
    "energyinstant_elec_cooling": "Instantaneous consumption (Electricity, Cooling)",
    "energyinstant_elec_cooling_max": "Instantaneous consumption (Electricity, Cooling) (maximum)",
    "energyinstant_elec_cooling_min": "Instantaneous consumption (Electricity, Cooling) (minimum)",
    "energyinstant_elec_heating": "Instantaneous consumption (Electricity, Heating)",
    "energyinstant_elec_heating_max": "Instantaneous consumption (Electricity, Heating) (maximum)",
    "energyinstant_elec_heating_min": "Instantaneous consumption (Electricity, Heating) (minimum)",
    "energyinstant_elec_hotwater": "Instantaneous consumption (Electricity, Hot water)",
    "energyinstant_elec_hotwater_max": "Instantaneous consumption (Electricity, Hot water) (maximum)",
    "energyinstant_elec_hotwater_min": "Instantaneous consumption (Electricity, Hot water) (minimum)",
    "energyinstant_elec_other": "Instantaneous consumption (Electricity, Other)",
    "energyinstant_elec_other_max": "Instantaneous consumption (Electricity, Other) (maximum)",
    "energyinstant_elec_other_min": "Instantaneous consumption (Electricity, Other) (minimum)",
    "energyinstant_elec_outlet": "Instantaneous consumption (Electricity, Outlets)",
    "energyinstant_elec_outlet_max": "Instantaneous consumption (Electricity, Outlets) (maximum)",
    "energyinstant_elec_outlet_min": "Instantaneous consumption (Electricity, Outlets) (minimum)",
    "energyinstant_elec_total": "Instantaneous consumption (Electricity, Total)",
    "energyinstant_elec_total_max": "Instantaneous consumption (Electricity, Total) (maximum)",
    "energyinstant_elec_total_min": "Instantaneous consumption (Electricity, Total) (minimum)",
    "energyinstant_elec_w": "Power (Electricity)",
    "energyinstant_elec_w_max": "Power (Electricity) (maximum)",
    "energyinstant_elec_w_min": "Power (Electricity) (minimum)",
    "energyinstant_gas_a": "Current (Gas)",
    "energyinstant_gas_a_max": "Current (Gas) (maximum)",
    "energyinstant_gas_a_min": "Current (Gas) (minimum)",
    "energyinstant_gas_cooling": "Instantaneous consumption (Gas, Cooling)",
    "energyinstant_gas_cooling_max": "Instantaneous consumption (Gas, Cooling) (maximum)",
    "energyinstant_gas_cooling_min": "Instantaneous consumption (Gas, Cooling) (minimum)",
    "energyinstant_gas_heating": "Instantaneous consumption (Gas, Heating)",
    "energyinstant_gas_heating_max": "Instantaneous consumption (Gas, Heating) (maximum)",
    "energyinstant_gas_heating_min": "Instantaneous consumption (Gas, Heating) (minimum)",
    "energyinstant_gas_hotwater": "Instantaneous consumption (Gas, Hot water)",
    "energyinstant_gas_hotwater_max": "Instantaneous consumption (Gas, Hot water) (maximum)",
    "energyinstant_gas_hotwater_min": "Instantaneous consumption (Gas, Hot water) (minimum)",
    "energyinstant_gas_other": "Instantaneous consumption (Gas, Other)",
    "energyinstant_gas_other_max": "Instantaneous consumption (Gas, Other) (maximum)",
    "energyinstant_gas_other_min": "Instantaneous consumption (Gas, Other) (minimum)",
    "energyinstant_gas_outlet": "Instantaneous consumption (Gas, Outlets)",
    "energyinstant_gas_outlet_max": "Instantaneous consumption (Gas, Outlets) (maximum)",
    "energyinstant_gas_outlet_min": "Instantaneous consumption (Gas, Outlets) (minimum)",
    "energyinstant_gas_total": "Instantaneous consumption (Gas, Total)",
    "energyinstant_gas_total_max": "Instantaneous consumption (Gas, Total) (maximum)",
    "energyinstant_gas_total_min": "Instantaneous consumption (Gas, Total) (minimum)",
    "energyinstant_gas_w": "Power (Gas)",
    "energyinstant_gas_w_max": "Power (Gas) (maximum)",
    "energyinstant_gas_w_min": "Power (Gas) (minimum)",
    "energyinstant_gaz_a": "Current (Gas)",
    "energyinstant_gaz_a_max": "Current (Gas) (maximum)",
    "energyinstant_gaz_a_min": "Current (Gas) (minimum)",
    "energyinstant_gaz_cooling": "Instantaneous consumption (Gas, Cooling)",
    "energyinstant_gaz_cooling_max": "Instantaneous consumption (Gas, Cooling) (maximum)",
    "energyinstant_gaz_cooling_min": "Instantaneous consumption (Gas, Cooling) (minimum)",
    "energyinstant_gaz_heating": "Instantaneous consumption (Gas, Heating)",
    "energyinstant_gaz_heating_max": "Instantaneous consumption (Gas, Heating) (maximum)",
    "energyinstant_gaz_heating_min": "Instantaneous consumption (Gas, Heating) (minimum)",
    "energyinstant_gaz_hotwater": "Instantaneous consumption (Gas, Hot water)",
    "energyinstant_gaz_hotwater_max": "Instantaneous consumption (Gas, Hot water) (maximum)",
    "energyinstant_gaz_hotwater_min": "Instantaneous consumption (Gas, Hot water) (minimum)",
    "energyinstant_gaz_other": "Instantaneous consumption (Gas, Other)",
    "energyinstant_gaz_other_max": "Instantaneous consumption (Gas, Other) (maximum)",
    "energyinstant_gaz_other_min": "Instantaneous consumption (Gas, Other) (minimum)",
    "energyinstant_gaz_outlet": "Instantaneous consumption (Gas, Outlets)",
    "energyinstant_gaz_outlet_max": "Instantaneous consumption (Gas, Outlets) (maximum)",
    "energyinstant_gaz_outlet_min": "Instantaneous consumption (Gas, Outlets) (minimum)",
    "energyinstant_gaz_total": "Instantaneous consumption (Gas, Total)",
    "energyinstant_gaz_total_max": "Instantaneous consumption (Gas, Total) (maximum)",
    "energyinstant_gaz_total_min": "Instantaneous consumption (Gas, Total) (minimum)",
    "energyinstant_gaz_w": "Power (Gas)",
    "energyinstant_gaz_w_max": "Power (Gas) (maximum)",
    "energyinstant_gaz_w_min": "Power (Gas) (minimum)",
    "energyinstant_max": "Instantaneous consumption (maximum)",
    "energyinstant_min": "Instantaneous consumption (minimum)",
    "energyinstant_water_a": "Current (Water)",
    "energyinstant_water_a_max": "Current (Water) (maximum)",
    "energyinstant_water_a_min": "Current (Water) (minimum)",
    "energyinstant_water_cooling": "Instantaneous consumption (Water, Cooling)",
    "energyinstant_water_cooling_max": "Instantaneous consumption (Water, Cooling) (maximum)",
    "energyinstant_water_cooling_min": "Instantaneous consumption (Water, Cooling) (minimum)",
    "energyinstant_water_heating": "Instantaneous consumption (Water, Heating)",
    "energyinstant_water_heating_max": "Instantaneous consumption (Water, Heating) (maximum)",
    "energyinstant_water_heating_min": "Instantaneous consumption (Water, Heating) (minimum)",
    "energyinstant_water_hotwater": "Instantaneous consumption (Water, Hot water)",
    "energyinstant_water_hotwater_max": "Instantaneous consumption (Water, Hot water) (maximum)",
    "energyinstant_water_hotwater_min": "Instantaneous consumption (Water, Hot water) (minimum)",
    "energyinstant_water_other": "Instantaneous consumption (Water, Other)",
    "energyinstant_water_other_max": "Instantaneous consumption (Water, Other) (maximum)",
    "energyinstant_water_other_min": "Instantaneous consumption (Water, Other) (minimum)",
    "energyinstant_water_outlet": "Instantaneous consumption (Water, Outlets)",
    "energyinstant_water_outlet_max": "Instantaneous consumption (Water, Outlets) (maximum)",
    "energyinstant_water_outlet_min": "Instantaneous consumption (Water, Outlets) (minimum)",
    "energyinstant_water_total": "Instantaneous consumption (Water, Total)",
    "energyinstant_water_total_max": "Instantaneous consumption (Water, Total) (maximum)",
    "energyinstant_water_total_min": "Instantaneous consumption (Water, Total) (minimum)",
    "energyinstant_water_w": "Power (Water)",
    "energyinstant_water_w_max": "Power (Water) (maximum)",
    "energyinstant_water_w_min": "Power (Water) (minimum)",
    "energyinstantcooli": "Current (Cooling)",
    "energyinstantcooli_max": "Current (Cooling) (maximum)",
    "energyinstantcooli_min": "Current (Cooling) (minimum)",
    "energyinstantcoolp": "Power (Cooling)",
    "energyinstantcoolp_max": "Power (Cooling) (maximum)",
    "energyinstantcoolp_min": "Power (Cooling) (minimum)",
    "energyinstantdhwi": "Current (Hot water)",
    "energyinstantdhwi_max": "Current (Hot water) (maximum)",
    "energyinstantdhwi_min": "Current (Hot water) (minimum)",
    "energyinstantdhwp": "Power (Hot water)",
    "energyinstantdhwp_max": "Power (Hot water) (maximum)",
    "energyinstantdhwp_min": "Power (Hot water) (minimum)",
    "energyinstantecsi": "Current (Hot water)",
    "energyinstantecsi_max": "Current (Hot water) (maximum)",
    "energyinstantecsi_min": "Current (Hot water) (minimum)",
    "energyinstantecsp": "Power (Hot water)",
    "energyinstantecsp_max": "Power (Hot water) (maximum)",
    "energyinstantecsp_min": "Power (Hot water) (minimum)",
    "energyinstantheati": "Current (Heating)",
    "energyinstantheati_max": "Current (Heating) (maximum)",
    "energyinstantheati_min": "Current (Heating) (minimum)",
    "energyinstantheatp": "Power (Heating)",
    "energyinstantheatp_max": "Power (Heating) (maximum)",
    "energyinstantheatp_min": "Power (Heating) (minimum)",
    "energyinstantti1i": "Current (TI1)",
    "energyinstantti1i_max": "Current (TI1) (maximum)",
    "energyinstantti1i_min": "Current (TI1) (minimum)",
    "energyinstantti1p": "Power (TI1)",
    "energyinstantti1p_max": "Power (TI1) (maximum)",
    "energyinstantti1p_min": "Power (TI1) (minimum)",
    "energyinstanttotelec": "Current (Electricity)",
    "energyinstanttotelec_max": "Current (Electricity) (maximum)",
    "energyinstanttotelec_min": "Current (Electricity) (minimum)",
    "energyinstanttotelec_p": "Power (Electricity)",
    "energyinstanttotelec_p_max": "Power (Electricity) (maximum)",
    "energyinstanttotelec_p_min": "Power (Electricity) (minimum)",
    "energyinstanttoteleci": "Current (Electricity)",
    "energyinstanttoteleci_max": "Current (Electricity) (maximum)",
    "energyinstanttoteleci_min": "Current (Electricity) (minimum)",
    "energyinstanttotelecp": "Power (Electricity)",
    "energyinstanttotelecp_max": "Power (Electricity) (maximum)",
    "energyinstanttotelecp_min": "Power (Electricity) (minimum)",
    "energyscalecooli": "Scale — Current (Cooling)",
    "energyscalecooli_max": "Scale — Current (Cooling) (maximum)",
    "energyscalecooli_min": "Scale — Current (Cooling) (minimum)",
    "energyscalecoolp": "Scale — Power (Cooling)",
    "energyscalecoolp_max": "Scale — Power (Cooling) (maximum)",
    "energyscalecoolp_min": "Scale — Power (Cooling) (minimum)",
    "energyscaledhwi": "Scale — Current (Hot water)",
    "energyscaledhwi_max": "Scale — Current (Hot water) (maximum)",
    "energyscaledhwi_min": "Scale — Current (Hot water) (minimum)",
    "energyscaledhwp": "Scale — Power (Hot water)",
    "energyscaledhwp_max": "Scale — Power (Hot water) (maximum)",
    "energyscaledhwp_min": "Scale — Power (Hot water) (minimum)",
    "energyscaleecsi": "Scale — Current (Hot water)",
    "energyscaleecsi_max": "Scale — Current (Hot water) (maximum)",
    "energyscaleecsi_min": "Scale — Current (Hot water) (minimum)",
    "energyscaleecsp": "Scale — Power (Hot water)",
    "energyscaleecsp_max": "Scale — Power (Hot water) (maximum)",
    "energyscaleecsp_min": "Scale — Power (Hot water) (minimum)",
    "energyscaleheati": "Scale — Current (Heating)",
    "energyscaleheati_max": "Scale — Current (Heating) (maximum)",
    "energyscaleheati_min": "Scale — Current (Heating) (minimum)",
    "energyscaleheatp": "Scale — Power (Heating)",
    "energyscaleheatp_max": "Scale — Power (Heating) (maximum)",
    "energyscaleheatp_min": "Scale — Power (Heating) (minimum)",
    "energyscaleti1i": "Scale — Current (TI1)",
    "energyscaleti1i_max": "Scale — Current (TI1) (maximum)",
    "energyscaleti1i_min": "Scale — Current (TI1) (minimum)",
    "energyscaleti1p": "Scale — Power (TI1)",
    "energyscaleti1p_max": "Scale — Power (TI1) (maximum)",
    "energyscaleti1p_min": "Scale — Power (TI1) (minimum)",
    "energyscaletotelec": "Scale — Current (Electricity)",
    "energyscaletotelec_max": "Scale — Current (Electricity) (maximum)",
    "energyscaletotelec_min": "Scale — Current (Electricity) (minimum)",
    "energyscaletotelec_p": "Scale — Power (Electricity)",
    "energyscaletotelec_p_max": "Scale — Power (Electricity) (maximum)",
    "energyscaletotelec_p_min": "Scale — Power (Electricity) (minimum)",
    "energyscaletoteleci": "Scale — Current (Electricity)",
    "energyscaletoteleci_max": "Scale — Current (Electricity) (maximum)",
    "energyscaletoteleci_min": "Scale — Current (Electricity) (minimum)",
    "energyscaletotelecp": "Scale — Power (Electricity)",
    "energyscaletotelecp_max": "Scale — Power (Electricity) (maximum)",
    "energyscaletotelecp_min": "Scale — Power (Electricity) (minimum)",
    "energytotindexwatt": "Consumption index (Electricity)",
    "finalize_association": "Configure {channel} as {usage}",
    "finalize_keypad": "Configure {channel} as a keypad",
    "finalize_remote": "Configure {channel} as a remote control",
    "finalize_switch": "Configure {channel} as a wall switch",
    "gsmlevel": "Mobile signal level",
    "heatsetpoint": "Heating setpoint",
    "histo": "History",
    "hvacmode": "Heating and cooling mode",
    "hygroin": "Humidity",
    "identify_device": "Identify device",
    "inactiveproduct": "Inactive product",
    "index": "Index",
    "indexstart": "Starting index",
    "indextimeon": "Operating time index",
    "interrupter_button": "Button {button_number}",
    "intrusion": "Intrusion",
    "intrusiondetect": "Intrusion",
    "irv1state": "State (IRV 1)",
    "irv2state": "State (IRV 2)",
    "irv3state": "State (IRV 3)",
    "irv4state": "State (IRV 4)",
    "irv5state": "State (IRV 5)",
    "irv6state": "State (IRV 6)",
    "irv7state": "State (IRV 7)",
    "irv8state": "State (IRV 8)",
    "irvcmd": "IRV command",
    "irvid": "IRV identifier",
    "isreference": "Reference device",
    "jobs": "Internal tasks",
    "jobsmp": "Main module tasks",
    "jobsrm": "Radio module tasks",
    "kerneldownloadforced": "Forced firmware download",
    "kerneluptodate": "Firmware up to date",
    "keyreference": "Radio module reference",
    "keyversionhw": "Radio hardware version",
    "keyversionstack": "Radio stack version",
    "keyversionsw": "Radio software version",
    "label": "Label",
    "last_usage": "Usage",
    "latitude": "Latitude",
    "level": "Level",
    "levelcmd": "Level command",
    "lightpower": "Solar irradiance",
    "livecheckrunning": "Live check in progress",
    "loaddefect": "Load defect",
    "loadsheddingon": "Load shedding",
    "localisation": "Location",
    "localmode": "Local operating mode",
    "localsetpoint": "Local setpoint",
    "localsetpremainingtimestr": "Local override time remaining",
    "longitude": "Longitude",
    "mac": "MAC address",
    "mainid": "Main module identifier",
    "mainreference": "Main module reference",
    "maintenance": "Maintenance",
    "maintenanceneeded": "Maintenance required",
    "mainversionhw": "Main hardware version",
    "mainversionsw": "Main software version",
    "manufacturer": "Manufacturer",
    "maxcoolsetpoint": "Maximum cooling setpoint",
    "maxdailyouttemp": "Daily maximum outdoor temperature",
    "maxheatsetpoint": "Maximum heating setpoint",
    "maxsetpoint": "Maximum temperature setpoint",
    "mincoolsetpoint": "Minimum cooling setpoint",
    "minheatsetpoint": "Minimum heating setpoint",
    "minsetpoint": "Minimum temperature setpoint",
    "modeasso": "Association mode",
    "modelidentifier": "Model identifier",
    "nbelem": "Number of elements",
    "nbrfactuators": "Number of radio actuators",
    "networkdefect": "Network fault",
    "obstacle_defect": "Obstacle detected",
    "obstacledefect": "Obstacle detected",
    "ondusk": "Dusk activation",
    "onfavpos": "Favourite position activation",
    "onpresencedetected": "Presence activation",
    "openingdetected": "Opening detected",
    "openstate": "Opening state",
    "outtemperature": "Outdoor temperature",
    "overrideremainingtime": "Override time remaining",
    "overridesetpoint": "Override setpoint",
    "part": "Alarm partition",
    "part1state": "State (PART 1)",
    "part2state": "State (PART 2)",
    "part3state": "State (PART 3)",
    "part4state": "State (PART 4)",
    "part5state": "State (PART 5)",
    "part6state": "State (PART 6)",
    "part7state": "State (PART 7)",
    "part8state": "State (PART 8)",
    "partcmd": "Alarm partition command",
    "password_empty": "Password empty",
    "pending_alarm_events": "Pending alarm events",
    "period": "Period",
    "periodoffset": "Period offset",
    "permissions": "Permissions",
    "plt_registered": "Platform registered",
    "position": "Position",
    "positioncmd": "Position command",
    "power": "Power",
    "prealarm": "Pre-alarm",
    "presencedetected": "Presence detected",
    "productconf": "Configuration",
    "productiondefect": "Production fault",
    "productname": "Product name",
    "protocol_available": "{protocol} — Available",
    "protocol_installed": "{protocol} — Installed",
    "protocol_ready": "{protocol} — Ready",
    "protocol_status": "{protocol} — Running",
    "readable": "Readable",
    "recfav": "Record favourite position",
    "refresh_energy": "Refresh energy data",
    "regtemperature": "Regulation temperature",
    "reload_devices": "Reload devices",
    "remote_button": "Button {button_number}",
    "remotesurveydefect": "Supervision fault",
    "remove_button": "Dissociate this button",
    "remove_device": "Permanently dissociate device",
    "remove_numbered_button": "Dissociate button {button_number}",
    "reset": "Reset",
    "selectedprog": "Selected programme",
    "sendasso": "Send association command",
    "sendnetremoteassomode": "Remote association mode",
    "setpoint": "Temperature setpoint",
    "shuttercmd": "Shutter command",
    "simdefect": "SIM card missing",
    "slope": "Heating curve slope",
    "softplan": "Software package",
    "softplan0": "Software package (0)",
    "softplan1": "Software package (1)",
    "softplan2": "Software package (2)",
    "softplan3": "Software package (3)",
    "softversion": "Software version",
    "softversion0": "Software version (0)",
    "softversion1": "Software version (1)",
    "softversion2": "Software version (2)",
    "softversion3": "Software version (3)",
    "speed": "Fan speed",
    "speedstring": "Fan speed",
    "start_product_association": "6. Start gateway listening",
    "state": "State",
    "summer_offset": "Summer time offset",
    "summeroffset": "Summer time offset",
    "supervisionmode": "Supervision mode",
    "synchropps": "Time synchronisation",
    "synchroradio": "Radio synchronisation",
    "systalarmdefect": "Alarm system fault",
    "systautoprotect": "Tamper alarm",
    "systbatterydefect": "Battery fault",
    "systopenissue": "Alarm arming blocked",
    "systsectordefect": "Mains supply error",
    "systsupervisiondefect": "Supervision fault",
    "systtechnicaldefect": "Technical defect",
    "techsmokedefect": "Smoke detected",
    "techwaterdefect": "Water leak detected",
    "temperature": "Temperature",
    "tempoon": "Time delay",
    "tempsensordefect": "Sensor defect",
    "tempsensoropencirc": "Sensor cut off",
    "tempsensorshortcut": "Sensor has short circuit",
    "thermic_defect": "Overheat",
    "thermicdefect": "Overheat",
    "thermiclevel": "Heating level",
    "thermostat": "Thermostat",
    "timedelay": "Time delay",
    "timeoncpt": "Operating time counter",
    "timezone": "Time zone",
    "toggle": "Toggle",
    "total": "Total",
    "tywell_shutters": "Shutters",
    "tywell_shutters_day": "Day shutters",
    "tywell_shutters_night": "Night shutters",
    "uid": "Device identifier",
    "unackedevent": "Unacknowledged events",
    "unitautoprotect": "Tamper alarm",
    "unitbatterydefect": "Battery fault",
    "unitinternaldefect": "Internal fault",
    "up_defect": "Raise not authorised",
    "update_available": "Update available",
    "updefect": "Raise not authorised",
    "usage": "Usage",
    "usemode": "Operating mode",
    "value": "Value",
    "videolinkdefect": "Video link error",
    "waterflowreq": "Requested water flow",
    "weather": "Weather",
    "writable": "Writable",
    "zclversion": "Zigbee cluster library version",
    "zone1state": "State (ZONE 1)",
    "zone2state": "State (ZONE 2)",
    "zone3state": "State (ZONE 3)",
    "zone4state": "State (ZONE 4)",
    "zone5state": "State (ZONE 5)",
    "zone6state": "State (ZONE 6)",
    "zone7state": "State (ZONE 7)",
    "zone8state": "State (ZONE 8)",
    "zonecmd": "Alarm zone command",
    "zones": "Alarm zones",
}


def set_entity_name(
    entity: Any,
    attribute: str,
    *,
    fallback_name: str | None = None,
    placeholders: dict[str, str] | None = None,
) -> None:
    """Set a native HA translation without changing the entity identity.

    A supplied ``_attr_name`` takes precedence over HA translations, even when
    its value is None. Remove the instance override for catalogue entries and
    keep an English description as the fallback for unsupported UI languages.
    Unknown gateway attributes stay available with a readable technical name.
    """
    key = attribute.lower()
    if (name := ENTITY_NAMES.get(key)) is None:
        raw_name = fallback_name or attribute
        entity._attr_name = re.sub(r"([a-z])([A-Z])", r"\1 \2", raw_name).replace(
            "_", " "
        )
        return
    with suppress(AttributeError):
        del entity._attr_name
    entity._attr_translation_key = key
    if placeholders:
        entity._attr_translation_placeholders = placeholders
        name = name.format_map(placeholders)
    description = getattr(entity, "entity_description", None)
    entity.entity_description = (
        replace(description, name=name, translation_key=key)
        if description is not None
        else EntityDescription(key=key, name=name, translation_key=key)
    )
