---
name: "Bug report"
description: "Report a bug with the integration"
labels: "Bug"
body:
- type: markdown
  attributes:
    value: Before you open a new issue, search through the existing issues to see if others have had the same problem.
- type: textarea
  attributes:
    label: "System Health details"
    description: "Paste the data from the System Health card in Home Assistant (https://www.home-assistant.io/more-info/system-health/#github-issues)."
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Checklist
    options:
      - label: I have enabled debug logging for my installation.
        required: true
      - label: I have filled out the issue template to the best of my ability.
        required: true
      - label: This report covers one problem only. Open a separate issue for each additional problem.
        required: true
      - label: I have searched the [existing open and closed issues](https://github.com/CyrilP/hass-deltadore-tydom-component/issues?q=is%3Aissue) and found no duplicate.
        required: true
- type: textarea
  attributes:
    label: "Describe the issue"
    description: "A clear and concise description of what the issue is."
  validations:
    required: true
- type: textarea
  attributes:
    label: Reproduction steps
    description: "Provide clear steps to reproduce the problem. Issues without sufficient information may be closed."
    value: |
      1.
      2.
      3.
      ...
  validations:
    required: true
- type: textarea
  attributes:
    label: "Debug logs"
    description: "Enable debug logging as described at https://www.home-assistant.io/integrations/logger/. Include the log from Home Assistant startup until the problem occurs, and remove all credentials and personal information."
    render: text
  validations:
    required: true

- type: textarea
  attributes:
    label: "Diagnostics dump"
    description: "Drag the diagnostics file here. See https://www.home-assistant.io/integrations/diagnostics/ for more information, and check that it contains no sensitive data."
