# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: warn
  logs:
    custom_components.deltadore-tydom: debug

